import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

test("the current target has deterministic named state and durable chat routes", async () => {
  const source = await readFile(join(ROOT, "index.js"), "utf8");
  for (const name of ["alpha", "beta"]) assert.match(source, new RegExp(`\\"${name}\\"`));
  assert.match(source, /initialState/);
  assert.match(source, /activationCount/);
  assert.match(source, /onStart\(\)/);
  assert.match(source, /setState/);
  assert.match(source, /this\.sql/);
  assert.match(source, /current\/names/);
  assert.match(source, /current\/state/);
  assert.match(source, /current-conformance-agent/);
  assert.match(source, /extends AIChatAgent/);
  assert.match(source, /onChatMessage/);
  assert.match(source, /streamText/);
  assert.match(source, /llama-swap\/Qwen3\.6-35B-A3B/);
  assert.match(source, /CREATE TABLE IF NOT EXISTS current_conformance_memories/);
  assert.match(source, /rememberFact:\s*tool\(/);
  assert.match(source, /listMemories:\s*tool\(/);
  assert.match(source, /summarizeMemories:\s*tool\(/);
  assert.match(source, /z\.string\(\)\.trim\(\)\.min\(1\)\.max\(MAX_MEMORY_LENGTH\)/);
  assert.match(source, /stopWhen: stepCountIs\(5\)/);
  assert.match(source, /CREATE TABLE IF NOT EXISTS current_conformance_reminders/);
  assert.match(source, /scheduleReminder:\s*tool\(/);
  assert.match(source, /listReminders:\s*tool\(/);
  assert.match(source, /cancelReminder:\s*tool\(/);
  assert.match(source, /idempotent:\s*true/);
  assert.match(source, /current\.pending >= MAX_PENDING_REMINDERS/);
  assert.match(source, /LIMIT \$\{MAX_REMINDER_HISTORY\}/);
  assert.match(source, /this\.schedule\(delaySeconds, "deliverReminder"/);
  assert.match(source, /this\.cancelSchedule\(id\)/);
  assert.match(source, /reminderId:\s*z\.string\(\)\.uuid\(\)/);
  assert.match(source, /WHERE reminder_id = \$\{reminderId\}/);
});
